//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSampleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM
    {
        public Nullable<int> EMPID { get; set; }
        public Nullable<long> EMPPHONENO { get; set; }
        public string EMPNAME { get; set; }
        public Nullable<int> EMPSALARY { get; set; }
        public string EMPROLE { get; set; }
        public string EMPADDR { get; set; }
        public string EMAILID { get; set; }
    }
}
