//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT
    {
        public int DEPTID { get; set; }
        public string DEPTNAME { get; set; }
        public Nullable<int> SID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
