//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public Nullable<int> Order_Id { get; set; }
        public OrderNumber Order_Num { get; set; }
        public Nullable<TypeOfId> Person_Id { get; set; }
    }
}
