//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.DEPTs = new HashSet<DEPT>();
            this.STUDENT1 = new HashSet<STUDENT>();
        }
    
        public int STDID { get; set; }
        public Nullable<int> STDROLLNO { get; set; }
        public string STDNAME { get; set; }
        public string STDCLASS { get; set; }
        public string STDRESULT { get; set; }
        public Nullable<int> STDDATE { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> MNGRID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT> DEPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENT1 { get; set; }
        public virtual STUDENT STUDENT2 { get; set; }
    }
}
