//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstSampleApp
{
    using System;
    
    public enum TypeOfId : short
    {
        PermanentID = 0,
        TemporaryID = 1
    }
}
